# Generated by Django 2.2.6 on 2019-10-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fidelityPoint',
            new_name='carteFid',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='payment',
            new_name='paiement',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='account',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastName',
        ),
        migrations.AddField(
            model_name='customer',
            name='compte',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='idClient',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='nom',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='prenom',
            field=models.CharField(default='', max_length=200),
        ),
    ]
