# Generated by Django 2.2.6 on 2019-10-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20191020_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='compte',
            new_name='Compte',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='credit',
            new_name='Credit',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='idClient',
            new_name='IdClient',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='nom',
            new_name='Nom',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='paiement',
            new_name='Paiement',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='prenom',
            new_name='Prenom',
        ),
    ]
