# Generated by Django 2.2.6 on 2019-10-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20191020_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='exclusivite',
            field=models.CharField(default='e-commerce', max_length=200),
            preserve_default=False,
        ),
    ]
