# Generated by Django 2.2.6 on 2019-10-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_produit_exclusivite'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='prixOriginel',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='reduction',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
