# Generated by Django 2.2.8 on 2019-12-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_clientpromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionsCustomersProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('IdClient', models.TextField()),
                ('codeProduit', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('reduction', models.IntegerField(default=0)),
            ],
        ),
    ]
