# Generated by Django 3.0.1 on 2020-01-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_promotionscustomersproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenteTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduit', models.TextField()),
                ('prix', models.PositiveIntegerField()),
                ('prixApres', models.PositiveIntegerField()),
                ('promo', models.PositiveIntegerField()),
                ('promo_client', models.PositiveIntegerField()),
                ('promo_client_produit', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('prix', models.PositiveIntegerField()),
                ('client', models.TextField()),
                ('pointsFidelite', models.PositiveIntegerField()),
                ('modePaiement', models.TextField()),
                ('articles', models.ManyToManyField(related_name='articles', to='ecommerce.VenteTicket')),
            ],
        ),
    ]
