# Generated by Django 3.0.1 on 2020-01-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20200117_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='articles',
        ),
        migrations.AddField(
            model_name='tickets',
            name='articles',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VenteTicket',
        ),
    ]
